// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zhieywexatjtbpkmmyda.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpoaWV5d2V4YXRqdGJwa21teWRhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0NDQ4NzYsImV4cCI6MjA2MjAyMDg3Nn0.TNkKu6s_jPTwyU2o8ZikaI_O1gN7H6LrNNRoX7bEjsg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);